### ISSUE TITLE
[Bug] "Wait for user input" is not stable

### ISSUE THREAD

**Issue by bassamtantawi-botpress** [botpress/studio#101]
In the studio, in the flow tab, you can go to any node and choose to "Wait for user message". However nothing is reflected on the flow UI:
![image](https://user-images.githubusercontent.com/89806971/133153176-ccde8428-a8e0-43e4-b03a-e4d2f877df5a.png)

But if you refreshed, then all nodes get the "wait for user message" notification on it:
![image](https://user-images.githubusercontent.com/89806971/133153295-0f8d90dd-bda9-452e-b227-75d19a87f4aa.png)

**Comment by bassamtantawi-botpress** [comment]
v12.26.1

**Comment by laurentlp** [comment]
Fixed with this PR https://github.com/botpress/studio/pull/98 and will be available in the next release of Botpress.
