### ISSUE TITLE
[BUG] using an underscore in the transition condition will add an undesired space

### ISSUE THREAD

**Issue by sebburon** [botpress/studio#104]
When using an underscore in a variable name, a space will be automatically added after the underscore and will make the transition fail.

To replicate the issue simply create a transition raw js like "{{user.my_test}}" 

When going back to the node a space will be added and the transition condition will look like this "user.my _test"

https://user-images.githubusercontent.com/16272318/133644214-9c12bde8-410a-4d60-98cc-0cb410b754e4.mp4

**Comment by laurentlp** [comment]
@sebburon Can you please add a screen recording of the issue so it's easier to reproduce?

**Comment by crochcunill** [comment]
Solved in version 12.26.7
