### ISSUE TITLE
[BUG] CMS not loading when ZH language is selected

### ISSUE THREAD

**Issue by sebburon** [botpress/studio#139]
When ZH language is selected at the bottom of the page and we go to the CMS section of the studio, the page is blank.

Error in the console: TypeError: undefined is not an object (evaluating 'o.startsWith')

Where it seems to break: https://github.com/botpress/studio/blob/0220da24965daa3b1e35a4599e7d14e82229a4dc/packages/studio-ui/src/web/views/Content/List.tsx#L238

**Comment by EFF** [comment]
quick fix missing null coalescing operator on line 237.
