### ISSUE TITLE
[BUG] UI issue when using multiple arguments in an action

### ISSUE THREAD

**Issue by sebburon** [botpress/studio#149]
When using multiple arguments in an action, it can create a UI issue depending on your screen size.

See this screenshot for a self-explanatory picture

<img width="723" alt="Screen Shot 2021-10-28 at 1 58 38 PM" src="https://user-images.githubusercontent.com/16272318/139309911-68e0f728-b655-423a-84a8-fc2c717ea217.png">

**Comment by daehli** [comment]
Do we want to limit the size of argument possible or adding an scrollbar ?
