### ISSUE TITLE
Standalone Studio

### ISSUE THREAD

**Issue by jonasfreitas-dev** [botpress/studio#18]
Hi, I'm very interested in using only the studio, standalone.

**I followed these steps:**
BP_MODULES_PATH: Path to the modules folder of a Botpress installation
BP_DATA_FOLDER: Path to the data folder (bots/, global/)

**this one I didn't understand very well, so I didn't set it up:**
BP_SERVER_URL: to determine

Even so I managed to run it, but it doesn't have a graphical interface.

I have a bot and tried to load it in studio but it gives me error 401.

As don't have access to the api, I don't see a way to authenticate or is there any way?

thanks in advance.

**Comment by allardy** [comment]
Hey @jonasfreitas-dev , the studio still needs to be executed by the main botpress process. Having it truely standalone will require more work and separation from the core. This is an intermediate step
