### ISSUE TITLE
[BUG] - Free trial should not be displayed when running pro version

### ISSUE THREAD

**Issue by laurentlp** [botpress/studio#207]
When a user is running a pro version of Botpress (BP_CONFIG_PRO_ENABLED=true) with a valid license, we should not recommend him to try a free version of what they already paid for.

Running **Botpress v12.26.7** and **Studio v0.0.43**

**Preview**

https://user-images.githubusercontent.com/9640576/142934607-fda11f4b-157a-4727-8091-54416f5c1de1.mp4

**Comment by J-FMartin** [comment]
Closing - already logged
