### ISSUE TITLE
[BUG] Debugger intent link breaks page

### ISSUE THREAD

**Issue by hacheybj** [botpress/studio#39]
Click the intent link in the debugger, and the page goes gray.

Refreshing the page does not help.

![2021-08-03_11-31-48](https://user-images.githubusercontent.com/59566773/128044052-1872a49e-861f-4593-850c-751a0fea0800.gif)

Studio 0.0.23

**Comment by ptrckbp** [comment]
That happened to me too. I added a fix in [this PR](https://github.com/botpress/studio/pull/44). Just waiting for approval :)
