### ISSUE TITLE
[BUG] Misunderstood - Changing Tab removes filters

### ISSUE THREAD

**Issue by hacheybj** [botpress/studio#41]
When changing tabs in the misunderstood module, the filter is removed (although not visually).

View video for reproduction
![misunder2](https://user-images.githubusercontent.com/59566773/128259303-f77ace91-5efe-416e-8e87-a5b956d10745.gif)

**Comment by ptrckbp** [comment]
There is a lot of application state that is not being recorded right now. I had similar issues just using normal navigation. I think maybe a more general approach might be in order.

**Comment by J-FMartin** [comment]
Fixed - closing
