### ISSUE TITLE
[BUG] studio is ready before the core when deploying Botpress Docker Image

### ISSUE THREAD

**Issue by poojapatil12** [botpress/studio#55]
Issue:

Deployment of Botpress 12.24 docker image is failing.
**Version 12.24.0
OS linux ubuntu_18_04**

When starting bp process it gives error:

`Error: connect ECONNREFUSED 127.0.0.1:3000 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {`

Full logs attached: [botpresslog_12.24-redacted.log](https://github.com/botpress/studio/files/6970582/botpresslog_12.24-redacted.log)

**Comment by charlescatta** [comment]
@allardy I believe that studio is calling `/api/internal/setStudioReady` on Botpress before it's started, I could fix this with a simple retry, what do you think?

**Comment by laurentlp** [comment]
Fixed with this PR https://github.com/botpress/studio/pull/105 and available in studio v0.0.37
