### ISSUE TITLE
[FEATURE] Add Explanations And Hints to Intents and Utterances

### ISSUE THREAD

**Issue by ptrckbp** [botpress/studio#57]
**Is your feature request related to a problem? Please describe.**
Intents and entities are not the most intuitive of concepts and are also completely optional. This is to make it easier for users to discover the power of Botpress.

**Describe the solution you'd like**
Add something like this to the NLU above "Tap + in the sidebar to define your first intent." : 
"Intents are groups of sentences that have a similar meaning, and should be treated similarly in your conversational flow." 
"Entities are words / phrases in your intent sentences that you want to extract"
"With these two, you can figure out what your user wants, and extract a piece of information like a name, date or number"
Hints can also be added to guide the user about what kind of utterances are needed.

**Describe alternatives you've considered**
There are a few overlapping ways of improving this, but I don't think this is exclusive with others. For instance, a tutorial might help more often than not, but if they are read quickly or skipped altogether, this will have more of an impact.

**Additional context**
Dialogflow does this (on top of having default intents), but I think they fall short by having explanations that are too technical. 
"Intents are mappings between a user's queries and actions fulfilled by your software. Read more here."
"Entities are objects your app or device takes action on. Read more here."

**Comment by J-FMartin** [comment]
Thanks - some of this will be handled in the new NLU Hint module in 2022.
