### ISSUE TITLE
[FEATURE]  Merge all non-empty bot templates into one bot template

### ISSUE THREAD

**Issue by ptrckbp** [botpress/studio#59]
**Is your feature request related to a problem? Please describe.**
If you want to find examples for actions, you open the weather bot, if you want intents, the welcome bot, and the smalltalk bot, more Q&A. Just moving around between the three templates doesn't really give much value, and you have to spend time looking for examples in each.

**Describe the solution you'd like**
Merge the three non-empty bot templates. If the flow is too complicated with welcome and weather, it can be moved to a sub-flow. 
The result is there will be an example bot, and an empty bot.

**Describe alternatives you've considered**
Creating a new example bot template, but that will be more time consuming. Another example is doing something like "Prebuilt Agents", but that would be way more time consuming.

**Additional context**

**Comment by J-FMartin** [comment]
Demo bots will be managed by the growth team @ Botpress

**Comment by J-FMartin** [comment]
Demo bots will be managed by the growth team @ Botpress
