### ISSUE TITLE
[bug] Emulator can overflow horizontally with simple elements

### ISSUE THREAD

**Issue by ptrckbp** [botpress/studio#80]
**Describe the bug**
This may be more or less intentional behavior, but I think it's a bug in the very least about the carrousel content type. 

**To Reproduce**

1. Go to flows
2. Add a carrousel with an image to the first node
3. open emulator, type something.
4. See horizontal scrolling

**Expected behavior**
Generally speaking, I would assume no overflow

**Screenshots**
![image](https://user-images.githubusercontent.com/87815239/131576071-400e6b5f-05d0-40aa-bedd-3513c637362e.png)

**Environment (please complete the following information):**

- OS: macOS
- Browser Chrome
- Browser Version Version 92.0.4515.131 (Official Build) (x86_64)
- Botpress Version 12.25.0
- NodeJS 12.13.0

**Additional context**
If you use a text element and markdown and include an image, the problem will be even bigger (image is not scaled at all). I'm not sure if this part is intentional or not.

**Comment by EFF** [comment]
fixed
